-- ============================================================================
-- BRIDGE FRAMEWORK — REAL ESTATE & PRIVATE ASSETS
-- DDL ported to Databricks SQL (Unity Catalog, Delta Lake)
--
-- Run on a Free-Edition serverless SQL Warehouse.
-- Idempotent: safe to re-run (uses CREATE TABLE IF NOT EXISTS).
--
-- Translation notes vs original T-SQL:
--   * Identity columns: BIGINT GENERATED BY DEFAULT AS IDENTITY (Databricks
--     identity columns must be BIGINT; semantics match SQL Server IDENTITY).
--   * Filtered indexes (`INDEX ix_x WHERE is_current = 1`) replaced with
--     Liquid Clustering on the same predicate columns. Delta auto-OPTIMIZE
--     handles file layout; PK/FK declarations are informational only.
--   * BIT → BOOLEAN, DATETIME2 → TIMESTAMP, NVARCHAR(MAX)/UNIQUEIDENTIFIER → STRING.
--   * Defaults: GETUTCDATE() → current_timestamp(); SYSTEM_USER → current_user().
--   * Row tracking and CDF enabled on all tables that may source MVs later.
--
-- Free Edition limitation:
--   * UNIQUE table constraints (informational, NOT ENFORCED) require
--     'spark.databricks.sql.dsv2.unique.enabled = true', which is disabled on
--     Free Edition. They're commented out below; uncomment on a paid workspace
--     where the flag is set. They're metadata only — uniqueness is not enforced
--     either way; application code remains responsible.
--   * Column DEFAULT values require the Delta table feature
--     'allowColumnDefaults' to be explicitly enabled. Set as a TBLPROPERTY on
--     every table that uses DEFAULT clauses (every table here does).
--   * Liquid Clustering does not support data skipping on BOOLEAN columns.
--     Originally is_current was included in CLUSTER BY for SCD2 query
--     optimization; it has been removed. Filtering on is_current = TRUE still
--     works correctly — Delta just won't prune files based on it. The other
--     clustering columns (enterprise_xxx_id, source_key, etc.) carry the
--     skipping load.
--   * Non-deterministic expressions (uuid(), rand(), random()) cannot be used
--     as column DEFAULTs in Delta. The execution_guid column on
--     bridge.execution_log was originally `DEFAULT uuid()` (NEWID() in T-SQL);
--     callers must now pass uuid() explicitly on INSERT.
-- ============================================================================

USE CATALOG workspace;

CREATE SCHEMA IF NOT EXISTS bridge;
CREATE SCHEMA IF NOT EXISTS dim;
CREATE SCHEMA IF NOT EXISTS fact;

-- ============================================================================
-- HELPER: Drop tables in correct order for clean rebuilds (development only)
-- Uncomment during development if you need to rebuild from scratch.
-- ============================================================================
/*
DROP TABLE IF EXISTS fact.position;
DROP TABLE IF EXISTS bridge.portfolio_entity_alloc;
DROP TABLE IF EXISTS bridge.portfolio_group_portfolio_alloc;
DROP TABLE IF EXISTS bridge.investor_portfolio_group_alloc;
DROP TABLE IF EXISTS bridge.key_crosswalk;
DROP TABLE IF EXISTS dim.security;
DROP TABLE IF EXISTS dim.asset;
DROP TABLE IF EXISTS dim.entity;
DROP TABLE IF EXISTS dim.portfolio;
DROP TABLE IF EXISTS dim.portfolio_group;
DROP TABLE IF EXISTS dim.investor;
DROP TABLE IF EXISTS dim.department_group;
DROP TABLE IF EXISTS dim.department;
DROP TABLE IF EXISTS bridge.key_domain;
DROP TABLE IF EXISTS bridge.source_registry;
DROP TABLE IF EXISTS bridge.bridge_tag;
DROP TABLE IF EXISTS bridge.tag;
DROP TABLE IF EXISTS bridge.bridge_definition;
DROP TABLE IF EXISTS bridge.bridge_category;
DROP TABLE IF EXISTS bridge.execution_detail_log;
DROP TABLE IF EXISTS bridge.execution_log;
*/

-- ============================================================================
-- SECTION 1: SOURCE & KEY METADATA
-- ============================================================================

-- 1.1 SOURCE REGISTRY ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS bridge.source_registry (
    source_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code         STRING       NOT NULL,
    source_name         STRING       NOT NULL,
    source_type         STRING       NOT NULL,    -- INTERNAL, EXTERNAL
    description         STRING,
    connection_type     STRING,                   -- API, SFTP, DATABASE, MANUAL
    refresh_frequency   STRING,                   -- REALTIME, DAILY, WEEKLY, MONTHLY
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP    NOT NULL DEFAULT current_timestamp(),
    created_by          STRING       NOT NULL DEFAULT current_user(),
    modified_at         TIMESTAMP,
    modified_by         STRING
    -- CONSTRAINT uq_source_registry_code UNIQUE (source_code)  -- disabled on Free Edition
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 1.2 KEY DOMAIN --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bridge.key_domain (
    domain_id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_code             STRING      NOT NULL,
    domain_name             STRING      NOT NULL,
    description             STRING,
    dimension_schema        STRING,
    dimension_table         STRING,
    dimension_key_column    STRING,
    is_active               BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING
    -- CONSTRAINT uq_key_domain_code UNIQUE (domain_code)  -- disabled on Free Edition
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 2: ORGANIZATIONAL STRUCTURE
-- ============================================================================

-- 2.1 DEPARTMENT --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.department (
    department_id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_department_id STRING      NOT NULL,
    department_code          STRING      NOT NULL,
    department_name          STRING      NOT NULL,
    description              STRING,
    is_active                BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by               STRING      NOT NULL DEFAULT current_user(),
    modified_at              TIMESTAMP,
    modified_by              STRING
    -- CONSTRAINT uq_department_enterprise_id UNIQUE (enterprise_department_id)  -- disabled on Free Edition
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 2.2 DEPARTMENT GROUP --------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.department_group (
    group_id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_group_id STRING      NOT NULL,
    department_id       BIGINT      NOT NULL,
    group_code          STRING      NOT NULL,
    group_name          STRING      NOT NULL,
    description         STRING,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by          STRING      NOT NULL DEFAULT current_user(),
    modified_at         TIMESTAMP,
    modified_by         STRING,

    -- CONSTRAINT uq_department_group_enterprise_id UNIQUE (enterprise_group_id),  -- disabled on Free Edition
    CONSTRAINT fk_department_group_dept FOREIGN KEY (department_id)
        REFERENCES dim.department(department_id) NOT ENFORCED
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 3: INVESTMENT HIERARCHY DIMENSIONS (SCD Type 2)
-- ============================================================================

-- 3.1 INVESTOR ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.investor (
    investor_sk             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_investor_id  STRING      NOT NULL,
    investor_name           STRING      NOT NULL,
    investor_type           STRING,
    investor_category       STRING,
    country_code            STRING,
    tax_id                  STRING,
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    record_source           STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING
)
CLUSTER BY (enterprise_investor_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 3.2 PORTFOLIO GROUP ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.portfolio_group (
    portfolio_group_sk              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_portfolio_group_id   STRING      NOT NULL,
    group_name                      STRING      NOT NULL,
    group_type                      STRING,
    strategy                        STRING,
    vintage_year                    INT,
    target_size                     DECIMAL(18,2),
    currency_code                   STRING      DEFAULT 'USD',
    -- SCD2
    is_current                      BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date            DATE        NOT NULL DEFAULT current_date(),
    effective_end_date              DATE,
    preceding_record_sk             BIGINT,
    succeeding_record_sk            BIGINT,
    -- Audit
    record_source                   STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at                      TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by                      STRING      NOT NULL DEFAULT current_user(),
    modified_at                     TIMESTAMP,
    modified_by                     STRING
)
CLUSTER BY (enterprise_portfolio_group_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 3.3 PORTFOLIO ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.portfolio (
    portfolio_sk            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_portfolio_id STRING      NOT NULL,
    portfolio_group_sk      BIGINT,
    portfolio_name          STRING      NOT NULL,
    portfolio_type          STRING,
    legal_structure         STRING,
    inception_date          DATE,
    termination_date        DATE,
    currency_code           STRING      DEFAULT 'USD',
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    record_source           STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_portfolio_pg FOREIGN KEY (portfolio_group_sk)
        REFERENCES dim.portfolio_group(portfolio_group_sk) NOT ENFORCED
)
CLUSTER BY (enterprise_portfolio_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 3.4 ENTITY ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.entity (
    entity_sk               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_entity_id    STRING      NOT NULL,
    portfolio_sk            BIGINT,
    entity_name             STRING      NOT NULL,
    entity_type             STRING,
    legal_structure         STRING,
    jurisdiction            STRING,
    tax_id                  STRING,
    formation_date          DATE,
    dissolution_date        DATE,
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    record_source           STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_entity_portfolio FOREIGN KEY (portfolio_sk)
        REFERENCES dim.portfolio(portfolio_sk) NOT ENFORCED
)
CLUSTER BY (enterprise_entity_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 3.5 ASSET -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.asset (
    asset_sk                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_asset_id     STRING      NOT NULL,
    entity_sk               BIGINT,
    managing_group_id       BIGINT,
    asset_name              STRING      NOT NULL,
    asset_type              STRING,
    property_subtype        STRING,
    address_line1           STRING,
    address_line2           STRING,
    city                    STRING,
    state_province          STRING,
    postal_code             STRING,
    country_code            STRING,
    latitude                DECIMAL(10,7),
    longitude               DECIMAL(10,7),
    square_feet             DECIMAL(18,2),
    unit_count              INT,
    year_built              INT,
    year_renovated          INT,
    acquisition_date        DATE,
    acquisition_price       DECIMAL(18,2),
    disposition_date        DATE,
    disposition_price       DECIMAL(18,2),
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    record_source           STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_asset_entity FOREIGN KEY (entity_sk)
        REFERENCES dim.entity(entity_sk) NOT ENFORCED,
    CONSTRAINT fk_asset_managing_group FOREIGN KEY (managing_group_id)
        REFERENCES dim.department_group(group_id) NOT ENFORCED
)
CLUSTER BY (enterprise_asset_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- 3.6 SECURITY ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim.security (
    security_sk             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_security_id  STRING      NOT NULL,
    asset_sk                BIGINT,
    security_name           STRING      NOT NULL,
    security_type           STRING,
    security_subtype        STRING,
    cusip                   STRING,
    isin                    STRING,
    ticker                  STRING,
    par_value               DECIMAL(18,4),
    coupon_rate             DECIMAL(8,5),
    maturity_date           DATE,
    currency_code           STRING      DEFAULT 'USD',
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    record_source           STRING      NOT NULL DEFAULT 'ENTERPRISE',
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_security_asset FOREIGN KEY (asset_sk)
        REFERENCES dim.asset(asset_sk) NOT ENFORCED
)
CLUSTER BY (enterprise_security_id)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 4: KEY CROSSWALK BRIDGE
-- ============================================================================
CREATE TABLE IF NOT EXISTS bridge.key_crosswalk (
    crosswalk_sk            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id               BIGINT      NOT NULL,
    source_system_id        BIGINT      NOT NULL,
    source_key              STRING      NOT NULL,
    source_key_secondary    STRING,
    target_system_id        BIGINT      NOT NULL,
    target_key              STRING      NOT NULL,
    target_key_secondary    STRING,
    relationship_type       STRING      NOT NULL DEFAULT 'ONE_TO_ONE',
    split_sequence          INT,
    split_description       STRING,
    -- SCD2
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    preceding_record_sk     BIGINT,
    succeeding_record_sk    BIGINT,
    -- Audit
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_xwalk_domain FOREIGN KEY (domain_id)
        REFERENCES bridge.key_domain(domain_id) NOT ENFORCED,
    CONSTRAINT fk_xwalk_source FOREIGN KEY (source_system_id)
        REFERENCES bridge.source_registry(source_id) NOT ENFORCED,
    CONSTRAINT fk_xwalk_target FOREIGN KEY (target_system_id)
        REFERENCES bridge.source_registry(source_id) NOT ENFORCED
)
CLUSTER BY (domain_id, source_system_id, source_key)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 5: POSITION FACT TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact.position (
    position_id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_date           DATE        NOT NULL,
    portfolio_sk            BIGINT      NOT NULL,
    entity_sk               BIGINT      NOT NULL,
    security_sk             BIGINT      NOT NULL,
    quantity                DECIMAL(18,4),
    market_value            DECIMAL(18,2),
    book_value              DECIMAL(18,2),
    cost_basis              DECIMAL(18,2),
    unrealized_gain_loss    DECIMAL(18,2),
    accrued_income          DECIMAL(18,2),
    unit_price              DECIMAL(18,6),
    price_source            STRING,
    local_currency_code     STRING,
    reporting_currency_code STRING      DEFAULT 'USD',
    fx_rate                 DECIMAL(18,8),
    record_source           STRING,
    source_position_id      STRING,
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    modified_at             TIMESTAMP,
    modified_by             STRING,
    CONSTRAINT fk_position_portfolio FOREIGN KEY (portfolio_sk)
        REFERENCES dim.portfolio(portfolio_sk) NOT ENFORCED,
    CONSTRAINT fk_position_entity FOREIGN KEY (entity_sk)
        REFERENCES dim.entity(entity_sk) NOT ENFORCED,
    CONSTRAINT fk_position_security FOREIGN KEY (security_sk)
        REFERENCES dim.security(security_sk) NOT ENFORCED
)
CLUSTER BY (position_date, portfolio_sk)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 6: OWNERSHIP / ALLOCATION TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS bridge.investor_portfolio_group_alloc (
    allocation_id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_sk             BIGINT      NOT NULL,
    portfolio_group_sk      BIGINT      NOT NULL,
    ownership_percentage    DECIMAL(8,5) NOT NULL,
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    CONSTRAINT fk_alloc_ipg_investor FOREIGN KEY (investor_sk)
        REFERENCES dim.investor(investor_sk) NOT ENFORCED,
    CONSTRAINT fk_alloc_ipg_pg FOREIGN KEY (portfolio_group_sk)
        REFERENCES dim.portfolio_group(portfolio_group_sk) NOT ENFORCED
)
CLUSTER BY (investor_sk, portfolio_group_sk)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.portfolio_group_portfolio_alloc (
    allocation_id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_group_sk      BIGINT      NOT NULL,
    portfolio_sk            BIGINT      NOT NULL,
    ownership_percentage    DECIMAL(8,5) NOT NULL,
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    CONSTRAINT fk_alloc_pgp_pg FOREIGN KEY (portfolio_group_sk)
        REFERENCES dim.portfolio_group(portfolio_group_sk) NOT ENFORCED,
    CONSTRAINT fk_alloc_pgp_p FOREIGN KEY (portfolio_sk)
        REFERENCES dim.portfolio(portfolio_sk) NOT ENFORCED
)
CLUSTER BY (portfolio_group_sk, portfolio_sk)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.portfolio_entity_alloc (
    allocation_id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_sk            BIGINT      NOT NULL,
    entity_sk               BIGINT      NOT NULL,
    ownership_percentage    DECIMAL(8,5) NOT NULL,
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    effective_start_date    DATE        NOT NULL DEFAULT current_date(),
    effective_end_date      DATE,
    created_at              TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by              STRING      NOT NULL DEFAULT current_user(),
    CONSTRAINT fk_alloc_pe_p FOREIGN KEY (portfolio_sk)
        REFERENCES dim.portfolio(portfolio_sk) NOT ENFORCED,
    CONSTRAINT fk_alloc_pe_e FOREIGN KEY (entity_sk)
        REFERENCES dim.entity(entity_sk) NOT ENFORCED
)
CLUSTER BY (portfolio_sk, entity_sk)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- ============================================================================
-- SECTION 7: BRIDGE FRAMEWORK METADATA (ETL orchestration layer)
-- ============================================================================

CREATE TABLE IF NOT EXISTS bridge.bridge_category (
    category_id     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code   STRING      NOT NULL,
    category_name   STRING      NOT NULL,
    description     STRING,
    source_table    STRING      NOT NULL,
    target_table    STRING      NOT NULL,
    delta_strategy  STRING      NOT NULL DEFAULT 'HASH',
    delta_column    STRING,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by      STRING      NOT NULL DEFAULT current_user(),
    modified_at     TIMESTAMP,
    modified_by     STRING
    -- CONSTRAINT uq_bridge_category_code UNIQUE (category_code)  -- disabled on Free Edition
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.bridge_definition (
    bridge_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT      NOT NULL,
    bridge_code     STRING      NOT NULL,
    bridge_name     STRING      NOT NULL,
    description     STRING,
    key_columns     STRING      NOT NULL,
    compare_columns STRING,
    priority        INT         NOT NULL DEFAULT 100,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by      STRING      NOT NULL DEFAULT current_user(),
    modified_at     TIMESTAMP,
    modified_by     STRING,

    -- CONSTRAINT uq_bridge_definition_code UNIQUE (bridge_code),  -- disabled on Free Edition
    CONSTRAINT fk_bridge_def_category FOREIGN KEY (category_id)
        REFERENCES bridge.bridge_category(category_id) NOT ENFORCED
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.tag (
    tag_id      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_code    STRING      NOT NULL,
    tag_name    STRING      NOT NULL,
    tag_group   STRING,
    description STRING,
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by  STRING      NOT NULL DEFAULT current_user()
    -- CONSTRAINT uq_tag_code UNIQUE (tag_code)  -- disabled on Free Edition
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.bridge_tag (
    bridge_id   BIGINT      NOT NULL,
    tag_id      BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    created_by  STRING      NOT NULL DEFAULT current_user(),
    CONSTRAINT pk_bridge_tag PRIMARY KEY (bridge_id, tag_id),
    CONSTRAINT fk_bt_bridge FOREIGN KEY (bridge_id)
        REFERENCES bridge.bridge_definition(bridge_id) NOT ENFORCED,
    CONSTRAINT fk_bt_tag FOREIGN KEY (tag_id)
        REFERENCES bridge.tag(tag_id) NOT ENFORCED
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.execution_log (
    execution_id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- execution_guid: callers must supply uuid() on INSERT.
    -- Delta rejects non-deterministic expressions (uuid(), rand()) as DEFAULTs.
    execution_guid      STRING      NOT NULL,
    category_id         BIGINT,
    tag_filter          STRING,
    execution_mode      STRING      NOT NULL DEFAULT 'FULL',
    status              STRING      NOT NULL DEFAULT 'RUNNING',
    started_at          TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    completed_at        TIMESTAMP,
    duration_seconds    DECIMAL(12,3),
    executed_by         STRING      NOT NULL DEFAULT current_user(),
    input_parameters    STRING,
    error_message       STRING,
    CONSTRAINT fk_exec_log_category FOREIGN KEY (category_id)
        REFERENCES bridge.bridge_category(category_id) NOT ENFORCED
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

CREATE TABLE IF NOT EXISTS bridge.execution_detail_log (
    detail_id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id        BIGINT      NOT NULL,
    bridge_id           BIGINT      NOT NULL,
    category_id         BIGINT      NOT NULL,
    status              STRING      NOT NULL DEFAULT 'RUNNING',
    started_at          TIMESTAMP   NOT NULL DEFAULT current_timestamp(),
    completed_at        TIMESTAMP,
    duration_seconds    DECIMAL(12,3),
    source_row_count    BIGINT,
    rows_inserted       BIGINT      DEFAULT 0,
    rows_updated        BIGINT      DEFAULT 0,
    rows_soft_deleted   BIGINT      DEFAULT 0,
    rows_unchanged      BIGINT      DEFAULT 0,
    keys_processed      BIGINT,
    sample_keys         STRING,
    error_message       STRING,
    error_detail        STRING,
    CONSTRAINT fk_detail_exec FOREIGN KEY (execution_id)
        REFERENCES bridge.execution_log(execution_id) NOT ENFORCED,
    CONSTRAINT fk_detail_bridge FOREIGN KEY (bridge_id)
        REFERENCES bridge.bridge_definition(bridge_id) NOT ENFORCED,
    CONSTRAINT fk_detail_category FOREIGN KEY (category_id)
        REFERENCES bridge.bridge_category(category_id) NOT ENFORCED
)
TBLPROPERTIES (
    -- Enables column DEFAULT values; required because every column with a DEFAULT
    -- clause needs this Delta table feature explicitly opted in.
    'delta.feature.allowColumnDefaults' = 'supported',
    -- Assigns each row a stable, monotonic _metadata.row_id and tracks commit
    -- versions per row. Required for materialized view incremental refresh
    -- (enzyme uses row IDs to compute deltas without full recomputation).
    'delta.enableRowTracking' = 'true',
    -- Exposes the change-data-feed via table_changes(). Lets downstream
    -- streaming tables and incremental consumers read inserts/updates/deletes
    -- as a stream of change events rather than re-scanning the whole table.
    'delta.enableChangeDataFeed' = 'true'
);

-- End of DDL.
SELECT 'Schema and tables created successfully.' AS status;
SELECT 'Schemas: bridge, dim, fact' AS info;
SELECT 'Dimension tables: dim.investor, dim.portfolio_group, dim.portfolio, dim.entity, dim.asset, dim.security' AS info;
SELECT 'Organizational: dim.department, dim.department_group' AS info;
SELECT 'Bridge tables: bridge.source_registry, bridge.key_domain, bridge.key_crosswalk' AS info;
SELECT 'Allocation tables: bridge.investor_portfolio_group_alloc, bridge.portfolio_group_portfolio_alloc, bridge.portfolio_entity_alloc' AS info;
SELECT 'Fact tables: fact.position' AS info;
