-- ============================================================================
-- BRIDGE FRAMEWORK — fact.transaction setup
--
-- Run after 04_seed_data.sql (positions must be seeded first so the dim
-- chain is populated for SCD2 temporal resolution).
--
-- =============================================================================
-- WHAT THIS FILE DOES
-- =============================================================================
--   1. CREATE TABLE fact.transaction with same SCD2-aware patterns as
--      fact.position
--   2. CREATE PROCEDURE bridge.usp_seed_transactions to populate it
--   3. CALL the procedure using session variables from 04
--
-- Volume target: ~20 transactions per security per year × 700 securities
-- × 20 years ≈ 280,000 rows.
--
-- The seed uses the same anchor + temporal-resolution pattern as Phase 7
-- of the position seed: each transaction's portfolio/entity/asset/security
-- SKs are resolved to the SCD2 version that was current on the transaction
-- date. Transactions for dates after a soft-deleted entity simply don't
-- generate (the temporal join eliminates them) — same realistic behavior
-- as positions.
-- ============================================================================

USE CATALOG workspace;

-- ============================================================================
-- SESSION VARIABLES (re-declared so file 15 can run standalone)
-- ============================================================================
-- Session variables don't persist across SQL editor sessions; if you ran
-- 04 in a previous session, those declarations are gone. We re-declare
-- here so this file is self-sufficient.
--
-- DECLARE OR REPLACE VARIABLE is idempotent — if 04 ran in this same
-- session, these statements just reset to defaults; if you want to keep
-- a non-default window, SET VARIABLE before running 15.
DECLARE OR REPLACE VARIABLE position_start_date DATE DEFAULT date_sub(current_date(), 365 * 20);
DECLARE OR REPLACE VARIABLE position_end_date   DATE DEFAULT current_date();

-- ============================================================================
-- TABLE: fact.transaction
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact.transaction (
    transaction_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_date        DATE                NOT NULL,
    settlement_date         DATE,
    portfolio_sk            BIGINT              NOT NULL,
    entity_sk               BIGINT              NOT NULL,
    security_sk             BIGINT              NOT NULL,
    transaction_type        STRING              NOT NULL  COMMENT 'BUY | SELL | ACQUISITION | DISPOSAL',
    quantity                DECIMAL(18,4)       NOT NULL  COMMENT 'Signed: positive for BUY/ACQUISITION, negative for SELL/DISPOSAL',
    price                   DECIMAL(18,4)       NOT NULL,
    gross_amount            DECIMAL(18,2)       NOT NULL  COMMENT 'quantity * price (signed)',
    fees                    DECIMAL(18,2)       NOT NULL  COMMENT 'Always positive',
    net_amount              DECIMAL(18,2)       NOT NULL  COMMENT 'gross - fees for BUY, gross + fees for SELL',
    counterparty            STRING,
    local_currency_code     STRING              NOT NULL  DEFAULT 'USD',
    reporting_currency_code STRING              NOT NULL  DEFAULT 'USD',
    fx_rate                 DECIMAL(18,6)       NOT NULL  DEFAULT 1.0,
    record_source           STRING              NOT NULL,
    created_at              TIMESTAMP           NOT NULL  DEFAULT current_timestamp(),
    modified_at             TIMESTAMP           NOT NULL  DEFAULT current_timestamp(),
    modified_by             STRING              NOT NULL  DEFAULT current_user(),
    -- Informational PKs/FKs
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id) NOT ENFORCED,
    CONSTRAINT fk_transaction_portfolio FOREIGN KEY (portfolio_sk) REFERENCES dim.portfolio NOT ENFORCED,
    CONSTRAINT fk_transaction_entity    FOREIGN KEY (entity_sk)    REFERENCES dim.entity    NOT ENFORCED,
    CONSTRAINT fk_transaction_security  FOREIGN KEY (security_sk)  REFERENCES dim.security  NOT ENFORCED
)
USING DELTA
CLUSTER BY (portfolio_sk, transaction_date)
TBLPROPERTIES (
    'delta.feature.allowColumnDefaults' = 'supported',  -- DEFAULT clauses on TIMESTAMP/DECIMAL columns
    'delta.enableRowTracking'           = 'true',       -- required for ROW_BASED MV refresh
    'delta.enableChangeDataFeed'        = 'true'        -- enables CDF for downstream pipelines
);

-- ============================================================================
-- PROCEDURE: bridge.usp_seed_transactions
-- ============================================================================
CREATE OR REPLACE PROCEDURE bridge.usp_seed_transactions(
    IN p_position_start_date DATE DEFAULT NULL,
    IN p_position_end_date   DATE DEFAULT NULL,
    IN p_days_between_txns   INT  DEFAULT 18    -- ≈ 20/year per security
)
COMMENT 'Generates fact.transaction over the given window using SCD2 temporal resolution.'
LANGUAGE SQL
SQL SECURITY INVOKER
BEGIN
    DECLARE v_start DATE;
    DECLARE v_end   DATE;

    SET v_start = COALESCE(p_position_start_date, date_sub(current_date(), 365 * 20));
    SET v_end   = COALESCE(p_position_end_date,   current_date());

    IF v_start > v_end THEN
        SIGNAL SQLSTATE '45100' SET MESSAGE_TEXT = 'p_position_start_date must be <= p_position_end_date';
    END IF;

    -- Idempotent
    DELETE FROM fact.transaction;

    -- ====================================================================
    -- Generation pipeline:
    --   1. For each enterprise_security_id, expand sequence of base dates
    --      every p_days_between_txns days across the window.
    --   2. Apply deterministic ±9-day jitter so transactions don't cluster
    --      on identical calendar days.
    --   3. Resolve dim chain (security → asset → entity → portfolio) at
    --      each transaction date using the canonical anchor + temporal
    --      version-at-date pattern.
    --   4. Compute transaction attributes (type, quantity, price, fees)
    --      deterministically from hashes — repeatable across reseeds.
    -- ====================================================================
    INSERT INTO fact.transaction (
        transaction_date, settlement_date,
        portfolio_sk, entity_sk, security_sk,
        transaction_type, quantity, price,
        gross_amount, fees, net_amount,
        counterparty, local_currency_code, reporting_currency_code, fx_rate,
        record_source
    )
    WITH
    distinct_securities AS (
        SELECT DISTINCT enterprise_security_id FROM dim.security
    ),
    base_dates AS (
        SELECT
            ds.enterprise_security_id,
            explode(sequence(v_start, v_end, make_interval(0, 0, 0, p_days_between_txns, 0, 0, 0))) AS base_date
        FROM distinct_securities ds
    ),
    jittered AS (
        SELECT
            enterprise_security_id,
            -- ±9 day jitter
            date_add(base_date, pmod(abs(hash(enterprise_security_id, base_date)), 19) - 9) AS txn_date,
            -- Transaction type: 40% BUY, 30% SELL, 15% ACQUISITION, 15% DISPOSAL
            element_at(
                array('BUY','BUY','BUY','BUY','SELL','SELL','SELL','ACQUISITION','DISPOSAL'),
                1 + pmod(abs(hash(enterprise_security_id, base_date, 'type')), 9)
            ) AS txn_type
        FROM base_dates
    ),
    resolved AS (
        -- Same SCD2 temporal resolution chain as fact.position Phase 7
        SELECT
            j.txn_date,
            j.txn_type,
            s_at_d.security_sk,
            s_at_d.par_value,
            e_at_d.entity_sk,
            p_at_d.portfolio_sk
        FROM jittered j
        -- SECURITY at date
        JOIN dim.security s_at_d
            ON s_at_d.enterprise_security_id = j.enterprise_security_id
           AND s_at_d.effective_start_date <= j.txn_date
           AND (s_at_d.effective_end_date IS NULL OR s_at_d.effective_end_date >= j.txn_date)
        -- ASSET: anchor → version at date
        JOIN dim.asset a_anchor ON a_anchor.asset_sk = s_at_d.asset_sk
        JOIN dim.asset a_at_d
            ON a_at_d.enterprise_asset_id = a_anchor.enterprise_asset_id
           AND a_at_d.effective_start_date <= j.txn_date
           AND (a_at_d.effective_end_date IS NULL OR a_at_d.effective_end_date >= j.txn_date)
        -- ENTITY: anchor → version at date
        JOIN dim.entity e_anchor ON e_anchor.entity_sk = a_at_d.entity_sk
        JOIN dim.entity e_at_d
            ON e_at_d.enterprise_entity_id = e_anchor.enterprise_entity_id
           AND e_at_d.effective_start_date <= j.txn_date
           AND (e_at_d.effective_end_date IS NULL OR e_at_d.effective_end_date >= j.txn_date)
        -- PORTFOLIO: anchor → version at date
        JOIN dim.portfolio p_anchor ON p_anchor.portfolio_sk = e_at_d.portfolio_sk
        JOIN dim.portfolio p_at_d
            ON p_at_d.enterprise_portfolio_id = p_anchor.enterprise_portfolio_id
           AND p_at_d.effective_start_date <= j.txn_date
           AND (p_at_d.effective_end_date IS NULL OR p_at_d.effective_end_date >= j.txn_date)
    ),
    enriched AS (
        SELECT
            r.*,
            -- Sign for the quantity
            CASE WHEN r.txn_type IN ('SELL','DISPOSAL') THEN -1 ELSE 1 END AS sign,
            -- Magnitude varies by type: ACQUISITION/DISPOSAL are 5-10x larger
            CASE WHEN r.txn_type IN ('ACQUISITION','DISPOSAL')
                 THEN 5000 + pmod(abs(hash(r.security_sk, r.txn_date, 'qty')), 5000)
                 ELSE 100 + pmod(abs(hash(r.security_sk, r.txn_date, 'qty')), 900)
            END AS qty_magnitude,
            -- Price = par_value × random factor in [0.85, 1.15]
            r.par_value * (0.85 + (pmod(abs(hash(r.security_sk, r.txn_date, 'px')), 31) * 0.01)) AS px
        FROM resolved r
    )
    SELECT
        txn_date                                               AS transaction_date,
        date_add(txn_date, 2)                                  AS settlement_date,  -- T+2
        portfolio_sk,
        entity_sk,
        security_sk,
        txn_type                                               AS transaction_type,
        cast(sign * qty_magnitude AS DECIMAL(18,4))            AS quantity,
        cast(px AS DECIMAL(18,4))                              AS price,
        cast(sign * qty_magnitude * px AS DECIMAL(18,2))       AS gross_amount,
        cast(qty_magnitude * px * 0.0015 AS DECIMAL(18,2))     AS fees,  -- 15bps fee
        cast(sign * qty_magnitude * px - (qty_magnitude * px * 0.0015) AS DECIMAL(18,2)) AS net_amount,
        element_at(
            array('Goldman Sachs','Morgan Stanley','JP Morgan','Citi','BAML','Barclays'),
            1 + pmod(abs(hash(security_sk, txn_date, 'cpty')), 6)
        )                                                      AS counterparty,
        'USD'                                                  AS local_currency_code,
        'USD'                                                  AS reporting_currency_code,
        cast(1.0 AS DECIMAL(18,6))                             AS fx_rate,
        element_at(
            array('STATE_STREET','BNY_MELLON','NORTHERN_TRUST'),
            1 + pmod(abs(hash(security_sk, txn_date, 'src')), 3)
        )                                                      AS record_source
    FROM enriched;

END;

-- ============================================================================
-- INVOKE
-- ============================================================================
-- DECLARE OR REPLACE makes these idempotent — if 04 already declared them
-- in the same session, this resets to the same defaults; if not, this
-- declares them fresh. Either way the CALL below has values to pass.
DECLARE OR REPLACE VARIABLE position_start_date DATE DEFAULT date_sub(current_date(), 365 * 20);
DECLARE OR REPLACE VARIABLE position_end_date   DATE DEFAULT current_date();

CALL bridge.usp_seed_transactions(
    p_position_start_date => position_start_date,
    p_position_end_date   => position_end_date
);

SELECT
    'fact.transaction seeded.' AS status,
    COUNT(*) AS row_count,
    MIN(transaction_date) AS earliest_txn,
    MAX(transaction_date) AS latest_txn
FROM fact.transaction;
